version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip
      - unzip -o terraform.zip
      - install terraform /usr/bin/ && rm -f terraform*
  pre_build:
    commands:
    - echo Logging in to Docker Hub...
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - REPOSITORY_URI=docker.io/$DOCKER_USER/esctfdemo    
    - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker images...
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo Starting Terraform Deployment...
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION="us-east-1"
    - terraform init
    - terraform apply -var "imagetag=$IMAGE_TAG" --auto-approve
 
 
 